### ISSUE TITLE
Did not discover <time> that arrived via actioncable/cableready

### ISSUE THREAD

**Issue by drnic** [stimulus-components/stimulus-timeago#4]
I am rendering new html via actioncable/cableready/morph, but the controller is not loading/rendering the `<time data-controller="timeago"...>` included in the new HTML.

**Comment by guillaumebriday** [comment]
Hum do you have some code to show or reproduction repo anywhere?

**Comment by drnic** [comment]
I'm sorry I didn't do a better job making the issue reproducible.

Yes, the controller was registered and worked as expected for normal usage. The glitch occurred when the HTML was replaced/morphed -- the new HTML was not being updated by the controller (say by a MutationObserver). At a glance, this controller works on initial connect().

I ended up going back to local_time.js, which does eventually update new `<time>` every minute or so I think.

Perhaps a new controller/impl is required that can watch the entire page for `<time>` as they come & go and automatically setup the behavior.

**Comment by drnic** [comment]
I've you've not experienced this issue, its ok to close the ticket. It can be reopened/re-discovered one day if someone else comes across the glitch. Or perhaps someone figures out what I was doing wrong :)

**Comment by guillaumebriday** [comment]
Hum after the morph, you see nothing or it does not refreshing only?

Maybe `this.isValid` in the `initialize` could be the problem here

**Comment by mbajur** [comment]
I'm facing the exact same problem. After morph, all the timers disappears.

**Comment by guillaumebriday** [comment]
Could you guys share a reproduction repo? I can't reproduce this issue at the moment :/
